version: '3.8'

services:
  angular-client:
    container_name: angular-ecommerce-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    restart: unless-stopped

